name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: jhunu383-sketch
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/github-contribution-grid-snake.svg"
          message: "Generate contribution snake"
